spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driverClassName: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true
    sql:
        init:
            platform: h2
            schema-locations: classpath:script.sql
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
